//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9040
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestProducts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/RestProducts")]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CategoryNameField;
        
        private string NameField;
        
        private int PriceField;
        
        private int ProductIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductListRest", ReplyAction="http://tempuri.org/IService1/GetProductListRestResponse")]
    RestProducts.Product[] GetProductListRest();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductRest", ReplyAction="http://tempuri.org/IService1/GetProductRestResponse")]
    RestProducts.Product GetProductRest(string ProductId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostProductRest", ReplyAction="http://tempuri.org/IService1/PostProductRestResponse")]
    RestProducts.Product[] PostProductRest(RestProducts.Product product);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutProductRest", ReplyAction="http://tempuri.org/IService1/PutProductRestResponse")]
    RestProducts.Product[] PutProductRest(RestProducts.Product product);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProductRest", ReplyAction="http://tempuri.org/IService1/DeleteProductRestResponse")]
    RestProducts.Product[] DeleteProductRest(string ProductId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public RestProducts.Product[] GetProductListRest()
    {
        return base.Channel.GetProductListRest();
    }
    
    public RestProducts.Product GetProductRest(string ProductId)
    {
        return base.Channel.GetProductRest(ProductId);
    }
    
    public RestProducts.Product[] PostProductRest(RestProducts.Product product)
    {
        return base.Channel.PostProductRest(product);
    }
    
    public RestProducts.Product[] PutProductRest(RestProducts.Product product)
    {
        return base.Channel.PutProductRest(product);
    }
    
    public RestProducts.Product[] DeleteProductRest(string ProductId)
    {
        return base.Channel.DeleteProductRest(ProductId);
    }
}
