//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpAutoTraining {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpAutoTraining.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file:///C:/Users/ssoptirean/Desktop/PagesTest/homepage.html#.
        /// </summary>
        internal static string ExpectedContactsFooterLinkHref {
            get {
                return ResourceManager.GetString("ExpectedContactsFooterLinkHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard page.
        /// </summary>
        internal static string ExpectedDashboardHeading {
            get {
                return ResourceManager.GetString("ExpectedDashboardHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard page.
        /// </summary>
        internal static string ExpectedDashboardPageTitle {
            get {
                return ResourceManager.GetString("ExpectedDashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default email: admin@domain.org.
        /// </summary>
        internal static string ExpectedDefaultEmailDisplayed {
            get {
                return ResourceManager.GetString("ExpectedDefaultEmailDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default password: 111111.
        /// </summary>
        internal static string ExpectedDefaultPasswordDisplayed {
            get {
                return ResourceManager.GetString("ExpectedDefaultPasswordDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details saved.
        /// </summary>
        internal static string ExpectedDetailsSavedMessage {
            get {
                return ResourceManager.GetString("ExpectedDetailsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address format is not valid.
        /// </summary>
        internal static string ExpectedEmailFormatError {
            get {
                return ResourceManager.GetString("ExpectedEmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address can&apos;t be null.
        /// </summary>
        internal static string ExpectedEmailNullError {
            get {
                return ResourceManager.GetString("ExpectedEmailNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file:///C:/Users/ssoptirean/Desktop/PagesTest/homepage.html.
        /// </summary>
        internal static string ExpectedHomeFooterLinkHref {
            get {
                return ResourceManager.GetString("ExpectedHomeFooterLinkHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string ExpectedHomepageHeading {
            get {
                return ResourceManager.GetString("ExpectedHomepageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string ExpectedHomepageTitle {
            get {
                return ResourceManager.GetString("ExpectedHomepageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password/email.
        /// </summary>
        internal static string ExpectedInvalidCredentialsError {
            get {
                return ResourceManager.GetString("ExpectedInvalidCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file:///C:/Users/ssoptirean/Desktop/PagesTest/wikipage.html.
        /// </summary>
        internal static string ExpectedWikiFooterLinkHref {
            get {
                return ResourceManager.GetString("ExpectedWikiFooterLinkHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki page.
        /// </summary>
        internal static string ExpectedWikiPageTitle {
            get {
                return ResourceManager.GetString("ExpectedWikiPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergiu.
        /// </summary>
        internal static string FirstNameData {
            get {
                return ResourceManager.GetString("FirstNameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaa@domain.org.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidEmail.com.
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaaa.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soptirean.
        /// </summary>
        internal static string LastNameData {
            get {
                return ResourceManager.GetString("LastNameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@domain.org.
        /// </summary>
        internal static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111111.
        /// </summary>
        internal static string ValidPassword {
            get {
                return ResourceManager.GetString("ValidPassword", resourceCulture);
            }
        }
    }
}
